/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSlugRouteImport } from './routes/_app/$slug'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as MainProjectsRouteImport } from './routes/_main/projects'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppCategoriesIndexRouteImport } from './routes/_app/categories/index'
import { Route as AppCategoriesSplatRouteImport } from './routes/_app/categories/$'
import { Route as MainAdminCategoriesRouteImport } from './routes/_main/admin.categories'
import { Route as MainProjectsIndexRouteImport } from './routes/_main/projects/index'
import { Route as MainProjectsCreateRouteImport } from './routes/_main/projects/create'
import { Route as MainAdminCategoriesIndexRouteImport } from './routes/_main/admin.categories/index'
import { Route as MainAdminCategoriesCreateRouteImport } from './routes/_main/admin.categories/create'
import { Route as MainProjectsIdEditRouteImport } from './routes/_main/projects/$id.edit'
import { Route as MainAdminCategoriesIdEditRouteImport } from './routes/_main/admin.categories/$id.edit'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSlugRoute = AppSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRouteRoute,
} as any)
const MainProjectsRoute = MainProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategoriesSplatRoute = AppCategoriesSplatRouteImport.update({
  id: '/categories/$',
  path: '/categories/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const MainAdminCategoriesRoute = MainAdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProjectsIndexRoute = MainProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainProjectsRoute,
} as any)
const MainProjectsCreateRoute = MainProjectsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => MainProjectsRoute,
} as any)
const MainAdminCategoriesIndexRoute =
  MainAdminCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainAdminCategoriesRoute,
  } as any)
const MainAdminCategoriesCreateRoute =
  MainAdminCategoriesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => MainAdminCategoriesRoute,
  } as any)
const MainProjectsIdEditRoute = MainProjectsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => MainProjectsRoute,
} as any)
const MainAdminCategoriesIdEditRoute =
  MainAdminCategoriesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => MainAdminCategoriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/$slug': typeof AppSlugRoute
  '/activity': typeof AppActivityRoute
  '/projects': typeof MainProjectsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/categories/$': typeof AppCategoriesSplatRoute
  '/admin/categories': typeof MainAdminCategoriesRouteWithChildren
  '/projects/create': typeof MainProjectsCreateRoute
  '/categories/': typeof AppCategoriesIndexRoute
  '/projects/': typeof MainProjectsIndexRoute
  '/admin/categories/create': typeof MainAdminCategoriesCreateRoute
  '/projects/$id/edit': typeof MainProjectsIdEditRoute
  '/admin/categories/': typeof MainAdminCategoriesIndexRoute
  '/admin/categories/$id/edit': typeof MainAdminCategoriesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/$slug': typeof AppSlugRoute
  '/activity': typeof AppActivityRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/categories/$': typeof AppCategoriesSplatRoute
  '/projects/create': typeof MainProjectsCreateRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/projects': typeof MainProjectsIndexRoute
  '/admin/categories/create': typeof MainAdminCategoriesCreateRoute
  '/projects/$id/edit': typeof MainProjectsIdEditRoute
  '/admin/categories': typeof MainAdminCategoriesIndexRoute
  '/admin/categories/$id/edit': typeof MainAdminCategoriesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_app/$slug': typeof AppSlugRoute
  '/_app/activity': typeof AppActivityRoute
  '/_main/projects': typeof MainProjectsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/_app/': typeof AppIndexRoute
  '/_app/categories/$': typeof AppCategoriesSplatRoute
  '/_main/admin/categories': typeof MainAdminCategoriesRouteWithChildren
  '/_main/projects/create': typeof MainProjectsCreateRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
  '/_main/projects/': typeof MainProjectsIndexRoute
  '/_main/admin/categories/create': typeof MainAdminCategoriesCreateRoute
  '/_main/projects/$id/edit': typeof MainProjectsIdEditRoute
  '/_main/admin/categories/': typeof MainAdminCategoriesIndexRoute
  '/_main/admin/categories/$id/edit': typeof MainAdminCategoriesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/$slug'
    | '/activity'
    | '/projects'
    | '/auth/sign-in'
    | '/categories/$'
    | '/admin/categories'
    | '/projects/create'
    | '/categories/'
    | '/projects/'
    | '/admin/categories/create'
    | '/projects/$id/edit'
    | '/admin/categories/'
    | '/admin/categories/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/$slug'
    | '/activity'
    | '/auth/sign-in'
    | '/categories/$'
    | '/projects/create'
    | '/categories'
    | '/projects'
    | '/admin/categories/create'
    | '/projects/$id/edit'
    | '/admin/categories'
    | '/admin/categories/$id/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_main'
    | '/auth'
    | '/_app/$slug'
    | '/_app/activity'
    | '/_main/projects'
    | '/auth/sign-in'
    | '/_app/'
    | '/_app/categories/$'
    | '/_main/admin/categories'
    | '/_main/projects/create'
    | '/_app/categories/'
    | '/_main/projects/'
    | '/_main/admin/categories/create'
    | '/_main/projects/$id/edit'
    | '/_main/admin/categories/'
    | '/_main/admin/categories/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$slug': {
      id: '/_app/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AppSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_main/projects': {
      id: '/_main/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof MainProjectsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/categories/$': {
      id: '/_app/categories/$'
      path: '/categories/$'
      fullPath: '/categories/$'
      preLoaderRoute: typeof AppCategoriesSplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_main/admin/categories': {
      id: '/_main/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof MainAdminCategoriesRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/projects/': {
      id: '/_main/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof MainProjectsIndexRouteImport
      parentRoute: typeof MainProjectsRoute
    }
    '/_main/projects/create': {
      id: '/_main/projects/create'
      path: '/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof MainProjectsCreateRouteImport
      parentRoute: typeof MainProjectsRoute
    }
    '/_main/admin/categories/': {
      id: '/_main/admin/categories/'
      path: '/'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof MainAdminCategoriesIndexRouteImport
      parentRoute: typeof MainAdminCategoriesRoute
    }
    '/_main/admin/categories/create': {
      id: '/_main/admin/categories/create'
      path: '/create'
      fullPath: '/admin/categories/create'
      preLoaderRoute: typeof MainAdminCategoriesCreateRouteImport
      parentRoute: typeof MainAdminCategoriesRoute
    }
    '/_main/projects/$id/edit': {
      id: '/_main/projects/$id/edit'
      path: '/$id/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof MainProjectsIdEditRouteImport
      parentRoute: typeof MainProjectsRoute
    }
    '/_main/admin/categories/$id/edit': {
      id: '/_main/admin/categories/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/categories/$id/edit'
      preLoaderRoute: typeof MainAdminCategoriesIdEditRouteImport
      parentRoute: typeof MainAdminCategoriesRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppSlugRoute: typeof AppSlugRoute
  AppActivityRoute: typeof AppActivityRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCategoriesSplatRoute: typeof AppCategoriesSplatRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSlugRoute: AppSlugRoute,
  AppActivityRoute: AppActivityRoute,
  AppIndexRoute: AppIndexRoute,
  AppCategoriesSplatRoute: AppCategoriesSplatRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface MainProjectsRouteChildren {
  MainProjectsCreateRoute: typeof MainProjectsCreateRoute
  MainProjectsIndexRoute: typeof MainProjectsIndexRoute
  MainProjectsIdEditRoute: typeof MainProjectsIdEditRoute
}

const MainProjectsRouteChildren: MainProjectsRouteChildren = {
  MainProjectsCreateRoute: MainProjectsCreateRoute,
  MainProjectsIndexRoute: MainProjectsIndexRoute,
  MainProjectsIdEditRoute: MainProjectsIdEditRoute,
}

const MainProjectsRouteWithChildren = MainProjectsRoute._addFileChildren(
  MainProjectsRouteChildren,
)

interface MainAdminCategoriesRouteChildren {
  MainAdminCategoriesCreateRoute: typeof MainAdminCategoriesCreateRoute
  MainAdminCategoriesIndexRoute: typeof MainAdminCategoriesIndexRoute
  MainAdminCategoriesIdEditRoute: typeof MainAdminCategoriesIdEditRoute
}

const MainAdminCategoriesRouteChildren: MainAdminCategoriesRouteChildren = {
  MainAdminCategoriesCreateRoute: MainAdminCategoriesCreateRoute,
  MainAdminCategoriesIndexRoute: MainAdminCategoriesIndexRoute,
  MainAdminCategoriesIdEditRoute: MainAdminCategoriesIdEditRoute,
}

const MainAdminCategoriesRouteWithChildren =
  MainAdminCategoriesRoute._addFileChildren(MainAdminCategoriesRouteChildren)

interface MainRouteRouteChildren {
  MainProjectsRoute: typeof MainProjectsRouteWithChildren
  MainAdminCategoriesRoute: typeof MainAdminCategoriesRouteWithChildren
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainProjectsRoute: MainProjectsRouteWithChildren,
  MainAdminCategoriesRoute: MainAdminCategoriesRouteWithChildren,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
